---
# tasks file for security-update

#- name: install yum-security for CentOS/RedHat
#  yum:
#    name: yum-security
#    state: latest

- name: 
  yum:
    list: security
  when: ansible_distribution in ["CentOS", "RedHat"]
  register: result

- debug: 
    msg: "{{ result }}"
    #  verbosity: 3

- name: install security updates
  yum:
    name: '*'
    security: yes
    state: latest
  when: ansible_distribution in ["CentOS", "RedHat"]
  
