---
# Playbook for aws ec2
-
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - securitygroup
    - ec2

- 
  hosts: "tag_Name_dragon*"
  vars:
    ansible_python_interpreter: "{{ client_python_path }}"

  # Roles: list of roles to be played
  roles:
    - nginx
    - hellonginx
    
