- name: include global variables
  include_vars:
    file: "{{ playbook_dir }}/roles/global/vars/main.yml"

- name: include global variables
  include_vars:
    file: "{{ playbook_dir }}/roles/global/vars/main.yml"

- name: create a network
  gcp_compute_network:
      name: "network-{{ project_name }}"
      project: "{{ gcp_project }}"
      # Create Custom-mode Network
      auto_create_subnetworks: "{{ auto_create_subnetworks }}"
      #ipv4_range: "{{ ipv4_range }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: network

- name: create a route
  gcp_compute_route:
    name: "route-{{ project_name }}"
    dest_range: "{{ destination_ranges }}"
    next_hop_gateway: "{{ next_hop_gateway }}"
    network: "{{ network }}"
    tags:
    - "{{ env_type }}"
    - databases
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: create a subnetwork
  gcp_compute_subnetwork:
    name: "subnetwork-{{ project_name }}-{{ env_type }}"
    region: "{{ gcp_region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ ipv4_range }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    private_ip_google_access: "{{ private_ip_google_access }}"
    state: present
  register: subnetwork

- name: create a firewall
  gcp_compute_firewall:
    name: "firewall-rules-{{ project_name }}"
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp

      ports: "{{ allowed_ports }}"
    # target_tags:
    # - test-ssh-server
    # - staging-ssh-server
    # source_tags:
    # - test-ssh-clients
    source_ranges: "{{ source_ranges }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
