---
# Full creation example with subnets and optional availability zones.
# The absence or presence of subnets deletes or creates them respectively.
- name: load vars from globe role
  include_vars: 
    file: "{{ playbook_dir }}/roles/global/vars/main.yml"

- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: "{{ project_name }}-{{ env }}-vpc"
    cidr_block: "{{ cidr_block }}"
    region: "{{ region_name }}"
    tags:
      env: "{{ env }}"
      project: "{{ project_name }}"
    tenancy: "{{ tenancy }}"
  register: vpcnet

# - 
#   debug: 
#     msg: "{{ vpcnet.vpc }}"

- name: create subnet
  ec2_vpc_subnet:
    #name: "{{ project_name }}-{{ env }}"     # not supported as of 06/21/2020
    state: present
    vpc_id: "{{ vpcnet.vpc.id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ region_name }}"
    tags: "{{ item.resource_tags }}"
    #tags: { "Environment":"Development" }
  with_items: 
    "{{ subnetworks }}"
  register: subnets

-
  debug:
    msg: "{{ subnets }}"
    
- name: create internet gateway 
  ec2_vpc_igw:
    vpc_id: "{{ vpcnet.vpc.id }}"
    state: present
  register: igw

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpcnet.vpc.id }}"
    region: "{{ region_name }}"
    tags:
      Name: "{{ public_route_table.name }}"
    subnets:
      "{{ public_route_table.subnets }}"
    routes:
      - dest: "{{ public_route_table.dest }}"
        gateway_id: "{{ igw.gateway_id }}"
  register: public_rt

- name: Set up private subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpcnet.vpc.id }}"
    region: "{{ region_name }}"
    tags:
      Name: "{{ private_route_table.name }}"
    subnets:
      "{{ private_route_table.subnets }}"
    routes:
      - dest: "{{ private_route_table.dest }}"
        gateway_id: "{{ igw.gateway_id }}"
  register: private_rt
