---
# vars file for global
vm_image: "projects/ubuntu-os-cloud/global/images/ubuntu-1910-eoan-v20200529"
gcp_project: hello-world-261815
gcp_cred_kind: serviceaccount
gcp_cred_file: ~/.ssh/ansible-gcp-key.json
gcp_region: us-central1
gcp_zone: us-central1-a

instance_names: [calmdown, peace]
machine_type: n1-standard-1
