---
# tasks file for runlevel

- name: load vars from globe role
  include_vars: 
    file: "{{ playbook_dir }}/roles/global/vars/{{ vars_file | default('main.yml') }}"

- name: set os run level
  command: command -v systemctl > /dev/null
  register: return_code

- name: change run level to 3 for systemd
  command: systemctl set-default multiple-uses.target
  when: {{ return_code }} and {{ runlevel }} != 3
  register: endpoint_runlevel

- name: change run level to 5 for systemd
  command: systemctl set-default multiple-uses.target
  when: {{ return_code }} and {{ runlevel }} != 5
  register: endpoint_runlevel

- name: change run level for sysVinit
  lineinfile:
    path: /etc/inittab
    regexp: '^id:?:initdefault:'
    line: "id:{{ runlevel }}:initdefault:"


# multi-user.target: analogous to runlevel 3
# graphical.target: analogous to runlevel 5

