---
# tasks file for ec2
- name: load vars from globe role
  include_vars: 
    file: "{{ playbook_dir }}/roles/global/vars/main.yml"

- name: Provision a set of instances
  ec2:
    key_name: "{{ key_pair_to_login_ec2 }}"
    group: "{{ security_group_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_name }}"
    user_data: |
          #!/bin/sh
          sudo yum install python3 -y ;
    region: "{{ target_region }}"
    wait: true
    exact_count: 1
    count_tag:
       Name: NginxWebservers
    instance_tags:
       Name: "{{ instance_name }}"
  ignore_errors: true
  register: ec2

- name: Refresh inventory to ensure new instances exist in inventory
  meta: refresh_inventory

- name: Wait for ssh connection to be ready.
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started 
  with_items: 
    - "{{ ec2.instances }}"

# Wait for ec2 initialization to be done (user_data finished)
# raw doesn't require python like shell command
- raw: test -e /var/lib/cloud/instance/boot-finished
  delegate_to: "{{ item.public_ip }}"
  retries: 40
  register: boot_finished
  changed_when: false
  until: boot_finished.rc == 0
  with_items: 
    - "{{ ec2.instances }}"
