---
# vars file for global
key_pair_to_login_ec2: Ansible-Virginia-Key-Pair
target_region: us-east-1

project_name: rain
security_group_name: "{{ project_name }}_sg"
instance_type: t2.micro
ami_name: ami-098f16afa9edf40be
instance_name: dragon
allow_ports: [22, 80, 443]
cidr_ip: 0.0.0.0/0
client_python_path: /usr/bin/python3
ansible_python_interpreter: /usr/bin/python3
nginx_doc_root: /usr/share/nginx/html
managed_by: "This web is provisioned with Ansible on host: {{ ansible_host }} created at: {{ ansible_date_time.iso8601 }}."
